[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM8
upload_protocol = esptool
board_build.partitions = minimal.csv  ; Usa partição mínima incluída no framework
board_build.f_cpu = 160MHz
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DDEBUG=0
lib_deps =
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit MPU6050@^2.0.6
    bblanchon/ArduinoJson@^6.21.4
    adafruit/DHT sensor library@^1.4.6
    knolleary/PubSubClient@^2.8.0